POST http://localhost:8080/achievements
Content-Type: application/json

{
  "commits": [
    {
      "id": "e21ee9533fd696f095525826773ed4642a8adcc4",
      "tree_id": "f03d75ee524d8dd9e228a48918ff8619e0d20f52",
      "distinct": true,
      "message": "that was awesome! wow!",
      "timestamp": "2021-02-14T19:02:29+02:00",
      "url": "https://github.com/example/gh-events-test/commit/e21ee9533fd696f095525826773ed4642a8adcc4",
      "author": {
        "name": "Bartosz Gałek",
        "email": "bartosz@github.com",
        "username": "bgalek"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [
        "my-file.txt"
      ],
      "removed": [],
      "modified": []
    },
    {
      "id": "e21ee9533fd696f095525826773ed4642a8adcc4",
      "tree_id": "f03d75ee524d8dd9e228a48918ff8619e0d20f52",
      "distinct": true,
      "message": "look at this! https://stackoverflow.com/questions/58978061/mono-to-flux",
      "timestamp": "2021-08-21T19:02:29+02:00",
      "url": "https://github.com/bgalek/gh-events-test/commit/e21ee9533fd696f095525826773ed4642a8adcc4",
      "author": {
        "name": "Bartosz Gałek",
        "email": "bartosz@github.com",
        "username": "bgalek"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [],
      "removed": [],
      "modified": []
    }
  ]
}

###

POST http://localhost:8080/integrations/github/events
Content-Type: application/json

{
  "zen": "Half measures are as bad as nothing at all.",
  "hook_id": 322267498,
  "hook": {
    "type": "App",
    "id": 322267498,
    "name": "web",
    "active": true,
    "events": [
      "meta",
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "url": "https://gh-stats.app/integrations/github/events"
    },
    "updated_at": "2021-10-08T06:33:20Z",
    "created_at": "2021-10-08T06:33:20Z",
    "app_id": 143440,
    "deliveries_url": "https://api.github.com/app/hook/deliveries"
  }
}

