app:
  db:
    host-and-db: ep-little-waterfall-al48863o-pooler.c-3.eu-central-1.aws.neon.tech/neondb
    options: sslmode=require&channel_binding=require
    username: neondb_owner
    password: placeholder

spring:
  application:
    name: gh-stats-api
  main:
    lazy-initialization: true
  r2dbc:
    url: r2dbc:postgresql://${app.db.host-and-db}?${app.db.options}
    username: ${app.db.username}
    password: ${app.db.password}
    pool:
      enabled: true
      initial-size: 0
      max-size: 5
      max-idle-time: 30s
      max-life-time: 10m
  flyway:
    url: jdbc:postgresql://${app.db.host-and-db}?${app.db.options}
    user: ${app.db.username}
    password: ${app.db.password}
    clean-disabled: false
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  codec:
    max-in-memory-size: 16MB
  jpa:
    open-in-view: false

server:
  forward-headers-strategy: FRAMEWORK
  error:
    whitelabel:
      enabled: false

github:
  app:
    id: 143440
    private-key: private-key
  webhook:
    secret: ""

cors:
  origins:
    - https://gh-stats.app
    - http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
