[versions]
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
test-logger = "4.0.0"
error-prone = "5.1.0"
error-prone-core = "2.50.0"
micrometer = "latest.release"
guava = "33.6.0-jre"
slugify = "4.0.1"
prettytime = "5.0.9.Final"
emoji-java = "5.1.1"
archunit = "1.5.0"
testcontainers = "1.21.4"

[libraries]
errorprone-core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "error-prone-core" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-starter-data-r2dbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-r2dbc" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
slugify = { group = "com.github.slugify", name = "slugify", version.ref = "slugify" }
prettytime = { group = "org.ocpsoft.prettytime", name = "prettytime", version.ref = "prettytime" }
emoji-java = { group = "com.vdurmont", name = "emoji-java", version.ref = "emoji-java" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc" }
postgresql = { group = "org.postgresql", name = "postgresql" }
r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql" }
r2dbc-pool = { group = "io.r2dbc", name = "r2dbc-pool" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
archunit = { group = "com.tngtech.archunit", name = "archunit", version.ref = "archunit" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-r2dbc = { group = "org.testcontainers", name = "r2dbc", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "error-prone" }
